apiVersion: apps/v1
kind: Deployment
metadata:
  name: beyond-mumbai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beyond-mumbai-app
  template:
    metadata:
      labels:
        app: beyond-mumbai-app
    spec:
      containers:
      - name: web-server
        image: 173378532619.dkr.ecr.us-east-1.amazonaws.com/beyond-mumbai:latest
        ports:
        - containerPort: 80

